version: '3.5'
networks:
  my-network:
    driver: bridge
services:
  db:
    image: postgres:14
    container_name: pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - my-network

  nodejs:
    build:
      context: ./user-auth
    container_name: node
    environment:
      - DB_URL=postgres://postgres:postgres@pg:5432/test_db
      - email=ubademy.14@gmail.com
      - pswd=Brancahdp123
      - secret=some
      - algorithm=HS256
    entrypoint: 'sh -c "sleep 10 && npm start"'
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - my-network

  python3c:
    build:
      context: ./cursos
    container_name: pythonCursos
    environment:
      - DB_URL=postgres://postgres:postgres@pg:5432/test_db
    entrypoint: 'sh -c "sleep 10 && uvicorn main:app --reload --host 0.0.0.0 --port 8081"'
    ports:
      - "81:8081"
    depends_on:
      - db
    networks:
      - my-network

  python3e:
    build:
      context: ./ubademy-exams
    container_name: pythonExams
    entrypoint: 'uvicorn main:app --reload --host 0.0.0.0 --port 8082'
    ports:
      - "82:8082"
    networks:
      - my-network

  gateway:
    build:
      context: ./
    container_name: gateway
    environment:
      - USERS_HOST=http://node:8080/
      - COURSES_HOST=http://pythonCursos:8081/
      - EXAMS_HOST=http://pythonExams:8082/
      - HASH_SECRET=some
      - HASH_ALGORITHM=HS256
    ports:
      - "5000:5000"
    networks:
      - my-network
